spring.application.name=Students
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/students
spring.datasource.username=postgres
spring.datasource.password=1127

mybatis.mapper-locations=classpath*:mapper/*.xml